[functions.webauthn-auth-options]
verify_jwt = false

[functions.webauthn-auth-verify]
verify_jwt = false

[functions.webauthn-register-options]
verify_jwt = false

[functions.webauthn-register-verify]
verify_jwt = false
